// <auto-generated />
using System;
using AlfaSoft.Contacts.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlfaSoft.Contacts.DataAccess.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    partial class MariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AlfaSoft.Contacts.Business.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("68dcb31a-5bbd-446f-8dee-20bb3eb8632e"),
                            ContactPhone = "234321234",
                            Email = "ozzy@devil.com",
                            Name = "Ozzy Orbourne"
                        },
                        new
                        {
                            Id = new Guid("7e73d7f6-8490-4614-a514-5ffb61f0996d"),
                            ContactPhone = "343234546",
                            Email = "david@spidersfrommars.com",
                            Name = "David Bowie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
